package test.PIMPage;

import org.testng.Assert;
import org.testng.annotations.Test;

import pageObjects.BasePage;
import pageObjects.HomePage;
import pageObjects.PIMPage;
import testBase.BaseClass;
import utilities.DataProviders;

public class TC03_PIMPage extends BaseClass
{
	@Test(dataProvider="Employee2Data",dataProviderClass=DataProviders.class)
	public void validEmloyeeId(String fname, String mname, String lname, String empid) throws InterruptedException 
	{ try {
		logger.info("****TC03_AddEmp Started****");
		HomePage hp = new HomePage(driver);
		PIMPage  pp = new PIMPage(driver);
		
		BasePage.Click(hp.lnkPIM);
		logger.info(" Clicked PIM link");
		BasePage.Click(pp.lnkaddemployee);
		logger.info(" Clicked Add Employee");
		
		logger.info("***  adding new employeee ***");
		BasePage.InputText(pp.txtfstname, fname);
		logger.info("Entered Firstname");
		BasePage.InputText(pp.txtmidname, mname);
		logger.info("Entered Middlename");
		BasePage.InputText(pp.txtlstname, lname);
		logger.info("Entered lastname");
		Thread.sleep(2000);
		BasePage.Clear(pp.txtempid);
		logger.info("Cleared AutoGenerated EmployeeId");
		BasePage.InputText(pp.txtempid1, empid);
		logger.info("Entered New EmployeeId");
		
		BasePage.Click(pp.btnsave);
		logger.info("Clicked Save Button");
		
		boolean prsnldetailpg = BasePage.ElementDisplayStatus(pp.txtempname);
		boolean empId_err_msg = BasePage.ElementDisplayStatus(pp.msgerrempId);
		
		if(prsnldetailpg==true)
		{
			logger.info("employee added sucessfully");
			BasePage.Click(pp.lnkaddemployee);
			Assert.assertTrue(true);
		}
		
		else if(empId_err_msg==true)
		{
			logger.info("error msg:" + BasePage.CaptureMsg(pp.msgerrempId));
			driver.navigate().refresh();
		}
		
		else
		{
			Assert.assertTrue(false);
		}
           
		   logger.info("****TC03_AddEmp Completed****");
	}
	catch(Exception e)
	{

		logger.error(e.getMessage());
		Assert.fail();
	}
	}

}
